### ISSUE TITLE
downloads broken

### ISSUE THREAD

**Issue by brentp** [lh3/hapdip#4]
the FTP downloads from `ftp://hengli-data:lh3data@ftp.broadinstitute.org/hapdip/` seem to no longer work. 
is there a way to access the bams?

**Comment by brentp** [comment]
specifically: `wget ftp://hengli-data:lh3data@ftp.broadinstitute.org/hapdip/CHM1.mem.bam` fails.

**Comment by lh3** [comment]
That file is gone. You can use the following instead:
```
ftp://ftp.sra.ebi.ac.uk/vol1/ERA596/ERA596286/bam/CHM1_1.bam
```

**Comment by brentp** [comment]
thanks.

**Comment by charliecurnin** [comment]
Could you also please provide an alternative for `wget ftp://hengli-data:lh3data@ftp.broadinstitute.org/hapdip/NA12878.mem.bam`?
